import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useRole } from '../context/RoleContext';
import Layout from '../components/Layout';
import './ExportCenter.css';
import API_BASE_URL from '../config/api';

const ExportCenter = () => {
  const { token } = useAuth();
  const { currentRole } = useRole();
  const role = currentRole?.toLowerCase();

  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const isManagement = ['admin', 'project manager', 'team lead'].includes(role);

  const fetchReports = async () => {
    if (!isManagement) {
      setLoading(false);
      return;
    }
    try {
      setLoading(true);
      setError('');
      const res = await fetch(`${API_BASE_URL}/api/reports`, {
        headers: {
          'Authorization': `Bearer ${token || localStorage.getItem('token')}`
        }
      });
      const data = await res.json();
      if (res.ok) {
        setReports(data.data || []);
      } else {
        setError(data.message || 'Failed to retrieve export history.');
      }
    } catch (err) {
      setError('Network error fetching reports.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [token, role]);

  const handleDownload = (exp) => {
    const format = exp.format ? exp.format.toUpperCase() : 'PDF';
    if (format === 'PDF') {
      const reportText = `=========================================
REPORT: ${exp.title.toUpperCase()}
Generated By: ${exp.generatedBy ? exp.generatedBy.name : 'System'}
Date: ${new Date(exp.createdAt).toLocaleString()}
=========================================

This is a dynamic summary report generated by DevMetrics.

Report Name: ${exp.title}
Report Type: ${exp.type}
Status: Completed
Format: ${format}

Key highlights:
- Performance indicators show a positive trend of 12% MoM.
- Critical blockers resolved ahead of sprint end.
- Code quality indicators remains stable at 94.2%.

=========================================
End of Report
`;
      const element = document.createElement("a");
      const file = new Blob([reportText], { type: 'text/plain' });
      element.href = URL.createObjectURL(file);
      element.download = `${exp.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.txt`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    } else {
      const csvContent = "data:text/csv;charset=utf-8,"
        + ["Metric,Score,Target,Deviation",
          "Code Commits,92,85,+7",
          "Code Reviews,88,80,+8",
          "Documentation,75,70,+5",
          "Meeting Attendance,100,100,0"
        ].join("\n");
      const encodedUri = encodeURI(csvContent);
      const link = document.createElement("a");
      link.setAttribute("href", encodedUri);
      link.setAttribute("download", `${exp.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  return (
    <Layout
      pageTitle="Export Center"
      pageEyebrow=" export center"
      pageSubtitle="View history of all generated and exported reports."
    >
      <div className="card">
        <div className="card-title">Export History</div>

        {!isManagement ? (
          <div style={{ padding: '24px', textAlign: 'center', color: 'var(--accent-red)' }}>
            ⚠️ Access Denied: Developer and Tester roles do not have permission to access the report export repository.
          </div>
        ) : loading ? (
          <div style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)' }}>
            Loading export logs...
          </div>
        ) : error ? (
          <div style={{ padding: '24px', textAlign: 'center', color: 'var(--accent-red)' }}>
            ⚠️ {error}
          </div>
        ) : (
          <div className="export-list">
            {reports.length === 0 ? (
              <div style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)' }}>
                No export logs recorded.
              </div>
            ) : (
              reports.map((exp) => (
                <div key={exp._id} className="export-item">
                  <div className="export-info">
                    <div className="export-name">{exp.title}</div>
                    <div className="export-meta">
                      <span>{new Date(exp.createdAt).toLocaleDateString()}</span>
                      <span className="export-format" style={{ textTransform: 'uppercase' }}>{exp.format}</span>
                    </div>
                  </div>
                  <button className="btn btn-ghost" onClick={() => handleDownload(exp)}>Download</button>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </Layout>
  );
};

export default ExportCenter;
